#%Vocabulary 1.0
base: http://a.ml/vocabularies/meta#
usage: Vocabulary containing meta-definitions
propertyTerms:
  describedBy:
    displayName: described by
    description: Link to the AML dialect describing a particular subgraph of information
    range: uri
