#%Vocabulary 1.0
vocabulary: security
base: http://a.ml/vocabularies/security#
usage: Vocabulary for HTTP security information
uses:
  doc: aml_doc.yaml
  data: data_model.yaml
classTerms:
  ApiKeySettings:
    displayName: APIKeySettings
    description: Settings for an API Key security scheme
    extends: Settings
  HttpApiKeySettings:
    displayName: HttpAPIKeySettings
    description: Settings for an Http API Key security scheme
    extends: Settings
  HttpSettings:
    displayName: HttpSettings
    description: Settings for an HTTP security scheme
    extends: Settings
  OAuth1Settings:
    displayName: OAuth1Settings
    description: Settings for an OAuth1 security scheme
    extends: Settings
  OAuth2Flow:
    displayName: OAuth2Flow
    description: Flow for an OAuth2 security scheme setting
  OAuth2Settings:
    displayName: OAuth2Settings
    description: Settings for an OAuth2 security scheme
    extends: Settings
  OpenIdConnectSettings:
    displayName: OpenIDSettings
    description: Settings for an OpenID security scheme
    extends: Settings
  ParametrizedSecurityScheme:
    displayName: ParametrizedSecurityScheme
  Scope:
    displayName: Scope
  SecurityRequirement:
    displayName: SecurityRequirement
    description: Flow for an OAuth2 security scheme setting
  SecurityScheme:
    displayName: SecurityScheme
    description: Authentication and access control mechanism defined in an API
  SecuritySchemeFragment:
    displayName: SecuritySchemeFragment
    description: Fragment encoding a RAML security scheme
    extends:
      - doc.Fragment
      - doc.Unit
  Settings:
    displayName: Settings
    description: Settings for a security scheme
propertyTerms:
  accessTokenUri:
    displayName: accessTokenURI
    range: string
  additionalProperties:
    displayName: additionalProperties
    range: data.Node
  authorizationGrant:
    displayName: authorizationGrant
    range: string
  authorizationUri:
    displayName: authorizationURI
    range: string
  bearerFormat:
    displayName: bearerFormat
    range: string
  flow:
    displayName: flow
    range: string
  flows:
    displayName: flows
    range: OAuth2Flow
  in:
    displayName: in
    range: string
  openIdConnectUrl:
    displayName: openIdConnectUrl
    range: string
  refreshUri:
    displayName: refreshURI
    range: string
  requestTokenUri:
    displayName: requestTokenURI
    range: string
  scheme:
    displayName: scheme
    range: SecurityScheme
  schemes:
    displayName: schemes
    range: ParametrizedSecurityScheme
  scope:
    displayName: scope
    range: Scope
  security:
    displayName: security
    description: Textual indication of the kind of security scheme used
    range: SecurityRequirement
  settings:
    displayName: settings
    description: Security scheme settings
    range: Settings
  signature:
    displayName: signature
    range: string
  tokenCredentialsUri:
    displayName: tokenCredentialsURI
    range: string
  type:
    displayName: type
    description: Type of security scheme
    range: string
